shuffle
bavly-adel/SWE-Assignment pull request #18
Opened 2018-12-01 23:10 UTC by Marwa-Safwat

2018-12-01 23:14 UTC, HossamHoussien reviewed
Please consider moving the `System.out.println()` statements into your function as the main will just simply call your function

2018-12-01 23:16 UTC, HossamHoussien commented
Please DON'T create another branch or a new pull request. Just edit your function, and then push it to your **EXISTING** branch, it will be updated here automatically.

2018-12-02 06:33 UTC, HossamHoussien approved these changes

2018-12-02 16:03 UTC, AhmedMaherAli approved these changes

2018-12-02 17:00 UTC, Bassant-Mohamed requested changes
this is not the whole master please check it again

2018-12-02 17:00 UTC, closed without merging